---
- hosts: coturn-ltc
  vars:
    coturn_rest: false
  vars_prompt:
    - name: "coturn_cli_password"
      prompt: "Enter coturn cli-password:"
      private: yes
      confirm: yes
  roles:
    - { role: base }
    - { role: letsencrypt }
    - { role: mysql }
    - { role: mysql-replication }
    - { role: coturn }
    - { role: munin }
